start:
  target:
    entity:
      integration: sunrise_alarm
      domain: switch
  fields:
    duration:
      example: 1
      selector:
        number:
          min: 0.5
          max: 180
          step: 0.5
          unit_of_measurement: min

stop:
  target:
    entity:
      integration: sunrise_alarm
      domain: switch

snooze:
  target:
    entity:
      integration: sunrise_alarm
      domain: switch
  fields:
    minutes:
      example: 9
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: min

set_days:
  target:
    entity:
      integration: sunrise_alarm
      domain: switch
  fields:
    days:
      required: true
      example: ["mon", "tue", "wed", "thu", "fri"]
      selector:
        select:
          multiple: true
          options: ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]

set_schedule:
  target:
    entity:
      integration: sunrise_alarm
      domain: switch
  fields:
    schedule:
      required: true
      example: { mon: "07:00:00", sat: "09:30:00" }
      selector:
        object:
